/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package traductor_lexico;

import java.io.BufferedReader;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JTextArea;
import javax.swing.SwingUtilities;



/**
 *
 * @author raufa
 */
public class interfazCompilador extends javax.swing.JFrame {

    /**
     * Creates new form interfazCompilador
     */
    public interfazCompilador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnLexico = new java.awt.Button();
        txtArea1 = new java.awt.TextArea();
        button2vdsvasd = new java.awt.Button();
        txtArea2 = new java.awt.TextArea();
        textArea3 = new java.awt.TextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnLexico.setActionCommand("Lexico");
        btnLexico.setBackground(new java.awt.Color(255, 255, 255));
        btnLexico.setLabel("Lexico");
        btnLexico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLexicoActionPerformed(evt);
            }
        });

        button2vdsvasd.setBackground(new java.awt.Color(255, 255, 255));
        button2vdsvasd.setLabel("Sintactico");
        button2vdsvasd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button2vdsvasdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(txtArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 19, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(button2vdsvasd, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(textArea3, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtArea1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(button2vdsvasd, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textArea3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addComponent(btnLexico, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtArea2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void button2vdsvasdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button2vdsvasdActionPerformed
     
     
       String textoIngresado=txtArea1.getText();
      
      
    String[] area = textoIngresado.split(" ");
    Lexical lexical;
    Sintactico sintactico;
    List<Token> tokens_analized;
    String bandera = "false";
    List<String> tokens = new ArrayList<>();
    
    try {
        for (String palabra : area) {
            tokens.add(palabra);
        }
        //String bandera="false";
        lexical = new Lexical(tokens);

        lexical.analize();

        tokens_analized = lexical.getResults();
        sintactico = new Sintactico(tokens_analized);
        Node root = sintactico.parse();



         String syntaxTree = sintactico.printTree(root, ""); 

           textArea3.setText(syntaxTree);
        
        Traductor_lexico.main(new String[] { textoIngresado, bandera });
        
        
    } catch (IOException e) {
        e.printStackTrace();
    }
    
       
           //Traductor_lexico.main(new String[] { textoIngresado });
       
    }//GEN-LAST:event_button2vdsvasdActionPerformed
    
    
    private void btnLexicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLexicoActionPerformed
    
   
    String textoIngresado = txtArea1.getText();
    String[] area = textoIngresado.split(" ");
    String bandera="false";
    Lexical lexical;
    List<Token> tokens_analyzed;
 
    List<String> tokens = new ArrayList<>();
   
    for (String palabra : area) {
        tokens.add(palabra);
    }
    
    lexical = new Lexical(tokens);
    lexical.analize();
    tokens_analyzed = lexical.getResults();
    LexicalUtil lexicalutil;
    
   
    StringBuilder tokenText = new StringBuilder();
    int i = 0;
    for (Token token : tokens_analyzed) {
        int num_val = token.num;
        String tokenInfo = "El token " + token.value + " es de tipo " + token.type + " " + num_val;
        tokenText.append(tokenInfo).append("\n");
        i++;
     }
    
    txtArea2.setText(tokenText.toString());
    
   
        //Traductor_lexico.main(new String[] { textoIngresado, bandera });
        // txtArea2.setText("hola");
   
    }//GEN-LAST:event_btnLexicoActionPerformed

    
    public void setTextArea3(String content) {
        System.out.println("Contiene= " + content);

        SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                textArea3.setText(content);
            }
        });
}




    public static void main(String args[]) {
       
        
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(interfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(interfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(interfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(interfazCompilador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

      
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new interfazCompilador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnLexico;
    private java.awt.Button button2vdsvasd;
    private java.awt.TextArea textArea3;
    private java.awt.TextArea txtArea1;
    private java.awt.TextArea txtArea2;
    // End of variables declaration//GEN-END:variables
}
